### ISSUE TITLE
Event on async completion of execution.

### ISSUE THREAD

**Issue by albertjan** [trinketapp/pypyjs#1]
Currently @bzwheeler implemented a hacky solution for this. I've read some documentation on it but I haven't seen anything that would help us. Might be a good idea to raise an issue over there and see what they say. I can't believe that there isn't some internal api that gets informed when the emterpreter is done executing.

**Comment by bzwheeler** [comment]
Opened issue in emscripten for advice.

https://github.com/kripken/emscripten/issues/3451
